name: Math 181
markdown: kramdown
url: sergeballif.github.io
baseurl: NSC-Math-181

title: Nsc-math-181
description: Guided Practice Assignments for Calculus 1
google_analytics: 
show_downloads: true



sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"

keywords: NSC, math, calculus

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
  twitter: sergeballif
  email: serge.ballif@nsc.edu
  github: sergeballif

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: placeholder.jpg
##comment this if you want full width posts with no sidebar
sidebar: on
