theme: jekyll-theme-dinky

name: Math 181
markdown: kramdown
url: sergeballif.github.io
baseurl: NSC-Math-181

title: NSC-Math-181
description: Syllabus for Math 181 - Calculus 1 at Nevada State College - Dr. Serge Ballif
google_analytics: 
show_downloads: true
